addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"     % "3.12.2")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"          % "2.3.1")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"     % "2.5.4")
addSbtPlugin("ch.epfl.scala"       % "sbt-tasty-mima"   % "1.3.0")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"      % "0.6.4")
