addSbtPlugin("com.timushev.sbt"    % "sbt-updates"      % "0.6.4")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"    % "0.11.0")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"     % "3.9.18")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"          % "2.2.1")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"     % "2.5.0")
