addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"           % "3.12.2")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"                % "2.3.1")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"       % "1.1.2")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"           % "2.5.5")
addSbtPlugin("ch.epfl.scala"       % "sbt-tasty-mima"         % "1.4.0")
addSbtPlugin("org.jmotor.sbt"      % "sbt-dependency-updates" % "1.2.9")
